### ISSUE TITLE
What is your opinion about our security issue?

### ISSUE THREAD

**Issue by randomwangran** [junwei-wang/.emacs.d#2]
[I would like to ask your suggestions: how we can improve the security of CASDUers to protect these people?](https://github.com/casdu/security-issue)

There's cetain things we don't want put them on-line for security issue.

- GPS data of single person

- any token/password

- personal information? (birthday,hometown,...)

list goes on...

Please comment anything you have and make suggestions.

The security issue to all casduer is the most important thing.

**Comment by randomwangran** [comment]
Don't get me wrong. No commitment, no responsibility. Just ask your suggestions.

**Comment by junwei-wang** [comment]
If you really care about confidentiality and privacy, please
 
- encrypt your sensitive information before uploading them to the cloud
- use some end-2-end encrypted message application

For non-expert users, usability is very important. You can try the following applications:

- Olvid / Signal for encrypted message (I prefer the first one)
- Keybase for both message and encrypted storage (like git)

For experts, you can try:

- git crypt: https://www.agwa.name/projects/git-crypt/
- GPG tools

**Comment by junwei-wang** [comment]
You can find me on keybase.

**Comment by randomwangran** [comment]
Thanks for those extremely useful info. I will study it and let you know how's going.
